### ISSUE TITLE
Error lors de la création d'une nouvelle liste quand on est connecté avec login/mdp

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#115]
Quand on est connecté avec un login/password, la création d'une nouvelle liste ne fonctionne pas. Elle est crée, mais l'utilisateur n'est pas ajouté comme owner. 

Retour : 
{ canSuggest: true
counts: {}
date: null
description: null
name: "liste_de_seraphin"
owner: false
owners: null
picture: "img/baby1.jpg"
privacy: "PRIVATE"
state: "LOGGED"
status: null
title: "liste de séraphin"
type: "BIRTH"
users: null }

**Comment by patou** [comment]
Je crois que dans l’ancienne version, c’est le front qui automatiquement ajoute le owner par défaut.
Mais rien dans la partie server.
