### ISSUE TITLE
Aperçu de la liste ne fonctionne plus

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#122]
On ne peut plus cliquer sur les boutons "en tant que Propriétaire, Participant, Public".
Cela ne permet pas de changer l'affichage de la liste en fonction des droits et comprendre le fonctionnement de la liste

**Comment by manudss** [comment]
On peut dans un premier temps cacher cette fonctionnalité et la rajouter plus tard.

**Comment by manudss** [comment]
commenter pour l'instant. En attandant de le corriger.
