### ISSUE TITLE
Retour sur l'application

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#131]
Test utilisateur par Emeline

- Bouton ajouter une envie, pas très visible
- Panier : pas compris la fonctionnalité
- Icone Corbeille affiche un tooltype "Archive"
- Bouton suivant lors de la création d'une liste, pas visible, le mettre à droite (ou au milieu), et en style bouton
- Selection d'une image, on n'a pas de retour que l'on a sélectionner une image (mettre un cadre autour), et pas d'indicateur comme quoi on peu sélectionner une image.
- Des fautes à corriger.
- La recherche dans une liste, ne fait la recherche que lorsque l'on quitte le champs

**Comment by manudss** [comment]
Certains des points sont corrigé dans la PR #136 👍 

- Bouton ajouter une envie, pas très visible
Ajout d'un tooltip
- Panier : pas compris la fonctionnalité
Renommé 
- Icone Corbeille affiche un tooltype "Archive"
Corbeille caché pour le moment
- Bouton suivant lors de la création d'une liste, pas visible, le mettre à droite (ou au milieu), et en style bouton
changé dans #136 
- Des fautes à corriger.
corrigé dans #136
