### ISSUE TITLE
n'affiche plus qui as offert une envie 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#142]
![image](https://user-images.githubusercontent.com/1046806/98471689-5f50dc80-21ee-11eb-998d-bbc38a784a1a.png)
lorsque d'une envie est marqué comme offert, cela devrait marqué par "sera offert par xxx" et un bouton je veux participer.

**Comment by manudss** [comment]
problème uniquement en prod !

**Comment by manudss** [comment]
Sur les données : 
![image](https://user-images.githubusercontent.com/1046806/98484456-e793a980-220f-11eb-9dc5-4677e4d66010.png)
le user take n'est mis. Surement un pb de migration avec les status ?

**Comment by manudss** [comment]
lié au  #143 . Cela a l'air d'être un pb de migration, car si tu fais offrir sur une nouvelle envie, cela fonctionne.

**Comment by patou** [comment]
Sur Test : 
<img width="893" alt="Capture d’écran 2020-11-08 à 23 39 13" src="https://user-images.githubusercontent.com/841858/98486136-d0f34f80-221b-11eb-9d0b-2c96d1130f35.png">
Sur Prod : 
<img width="973" alt="Capture d’écran 2020-11-08 à 23 39 35" src="https://user-images.githubusercontent.com/841858/98486141-d9e42100-221b-11eb-95b7-2be73837f224.png">

Donc il y a le même problème, les deux ont bien un userTake de remplis.
Ce que j'ai l'impression, c'est que si il y a plusieurs participants qui offre, ça s'affiche pas.

![image](https://user-images.githubusercontent.com/841858/98486190-24fe3400-221c-11eb-9549-eeecf7bab539.png)

**Comment by manudss** [comment]
celui avec que un, c'est un que tu viens de faire ? ou un ancien. Pour moi c'est tous les anciens qui ont ce pb !

**Comment by patou** [comment]
> celui avec que un, c'est un que tu viens de faire ? ou un ancien. Pour moi c'est tous les anciens qui ont ce pb !

Non, on l'a fait cette semaine, je sais pas si tu as une notification, et donc savoir quand on l'a fait.
Mais on a rien modifier sur la liste depuis la mise en prod.

**Comment by manudss** [comment]
ba maintenant cela s'affiche : 
![image](https://user-images.githubusercontent.com/1046806/98486755-807df100-221f-11eb-8fb8-50c703c05ef3.png)

**Comment by manudss** [comment]
Parce qu'elle vient de l'éditer, donc cela a remis bien. mets a jour l'abonnement de pomme d'api sur la liste d'apoline pour voir ?

**Comment by patou** [comment]
Non je ne vois pas votre Sera offert par Manu et Suzanne.

Es-ce que l'on ne voit pas que les envies que l'on offre nous ?

**Comment by patou** [comment]
Trouvé, il y a un ngIf sur l'affichage de qui donne les envies, et qui s'affiche que si userGiven est true, or ce champs est true si l'utilisateur fait partis de ceux qui donnent l'envie.
