### ISSUE TITLE
Afficher l'image des utilisateurs

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#22]

**Comment by patou** [comment]
On peut la récupérer, par : 
http://picasaweb.google.com/data/entry/api/user/email

Puis dans le résultat parser le xml et récupérer le gphoto:thumbnail

**Comment by manudss** [comment]
avec l'authentification via firebase, on récupére l'image.

**Comment by manudss** [comment]
fait dans la v7

**Comment by patou** [comment]
Oui mais seulement pour la connexion Google. Il faudrait pouvoir ajouter une image en mode email.
