### ISSUE TITLE
Ne pas recharger la liste à chaque changement. 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#24]
On recharge tout, dès que l'on modifie, on envoie un commentaire. On devrait pas. Peut-être avoir un push du serveur à chaque changement. Ou du moins avoir synchro en arrière plan.

**Comment by patou** [comment]
Oui, surtout que c'est lent !
Push du serveur c'est compliqué, après, on a pas besoin de rafraichir, car on a tous dans notre page.

**Comment by manudss** [comment]
Si tu as les nouveaux commentaires, et cadeau pris.

**Comment by patou** [comment]
Tu fais un bouton rafraîchir, ou alors, tu ne fais pas l'affichage du chargement.

**Comment by manudss** [comment]
Fait pour certains changements. (avec Masonry, cela a refait ce problème). J'ai ajouté un bouton pour raffraichir.
