### ISSUE TITLE
Pouvoir se connecter avec différents types de compte

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#30]
Pouvoir se connecter, non pas seulement avec un compte Google, mais aussi avec Facebook Et D'autres types De Compte. A Voir avec un script qui gère tous les types de comptes.

**Comment by patou** [comment]
Ou un email et un mot de passe spécifique à l'application !

**Comment by manudss** [comment]
fait dans le v7 : avec compte normal, google et facebook. Possibbilité d'en rajouter d'autre via firebase.
