### ISSUE TITLE
Avoir un bookmarklet

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#31]
Un bouton que l'on peux mettre en favoris qui lorsque l'on clique exécute un javascript qui permettra alors d'ajouter la page dans la liste d'envie.

**Comment by manudss** [comment]
Exemple de code, pour créer un bookmaklet qui affiche une pop-up un formulaire (à remplacer par notre page). 


`javascript:(function(){ function centeredPopupPosition(w, h) {var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left; var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top; var width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width; var height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height; var left = ((width / 2) - (w / 2)) + dualScreenLeft; var top = ((height / 2) - (h / 2)) + dualScreenTop; return [left, top]; } var width = 400, height = 250, position = centeredPopupPosition(width, height); window.open('http://booky.io/add.php?url='+encodeURIComponent(document.location.href)+'&title='+encodeURIComponent(document.title),'bookyBookmarklet','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=' + width + ',height=' + height + ',top=' + position[1] + ',left=' + position[0]).focus(); }());`

**Comment by manudss** [comment]
Autre exemple : 
`javascript:(function(){try{var x=document.getElementsByTagName('head').item(0);var o=document.createElement('script');if('object'!=typeof(o)){o=document.standardCreateElement('script');}o.setAttribute('src','http://www.wishlist.com/bookmarklet/custom_bookmarklet.js');o.setAttribute('type','text/javascript');x.appendChild(o);}catch(e){alert('Error: '+e);}})();`
script : 
http://www.wishlist.com/bookmarklet/custom_bookmarklet.js
