### ISSUE TITLE
Filtrer et valider les emails lors de la création et le partage d'une liste. 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#32]

**Comment by manudss** [comment]
faire un trim() url.

**Comment by manudss** [comment]
Faire aussi un toLowerCase (car si il y a une majuscule, cela n'est pas reconnu.

**Comment by manudss** [comment]
dans le premier champs texte, si on copie les mail avec des ';' cela est ajouté dans un seul champ utilisateur.

**Comment by patou** [comment]
Le champ pour le owner ?
