### ISSUE TITLE
Definir un type pour la liste et date 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#35]
Par exemple : Noël, anniversaire,  fête etc... 

Adapter l'affichage en fonction de ce type. (image de fond, couleurs thème, icone de liste...) 

Afficher un compte à rebour pour la liste.

**Comment by patou** [comment]
Je sais pas, car ma liste, si j'ai des cadeaux non offert, je les laisse dans ma liste pour mon anniversaire ?
