### ISSUE TITLE
Timeline et notification des dernières modifs sur les listes que l'on suit

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#36]
Lié à la notification mail,  mais d'avoir une timeline serait sympa. 

Il faut enregistrer tous les changements. Pour cela créer un object notification avec les changements effectués. 

Les différents changements :
- ajout d'une envie
- modification d'une envie 
- ajout d'une image ou d'un lien
- ajout d'un commentaire. 
- participer à un cadeau (ou anuler un cadeau). 

Filtrer en fonction des droits.

**Comment by patou** [comment]
Je pense qu'il serait bien, c'est d'avoir le contenu du changement dans le mail, pas juste, il y a une nouvelle envie, etc ?

**Comment by manudss** [comment]
Oui, c'est donc voir et décider, comment on stock cela en bdd ? Est-ce qu'on copie, le contenu, l'object entier ? On fait juste un lien. On mets le texte, avant et après etc...

Durée de rétention ? etc...
