### ISSUE TITLE
Options pour rendre une liste non privée. 

### ISSUE THREAD

**Issue by manudss** [patou/liste-envies#39]
Avoir un fonctionnement, comme toutes les autres listes.

**Comment by patou** [comment]
Le problème c'est la requete qui fait donne moi toutes les listes où je suis partagé, tu ne peux pas faire de ou !
Ou alors, les listes publiques ne sont pas listé dans la liste de mes listes.
Et dès que l'on interagit avec la liste, on est ajouté dans la liste des utilisateurs.

C'est un peu lié à l'amélioration #29 qui est de pouvoir faire une lien vers sa liste, et que si on accède à la liste, on est alors automatiquement ajouté comme personnes de la liste.
