### ISSUE TITLE
Supprimer les emails

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#54]
Supprimer les emails dans les owners.

**Comment by manudss** [comment]
@patou ? cela correspond à quoi ? Est-ce encore d'activité.

**Comment by patou** [comment]
Je sais plus. Es ce que c'était pas ne plus afficher l'émail des personnes ?

**Comment by manudss** [comment]
Afficher le nom au lieu de l'email ? Dans cela cas là c'est bon. On peut cloturer.
