### ISSUE TITLE
Permettre de voir sa liste de cadeaux à offrir

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#7]

**Comment by manudss** [comment]
Tu entends quoi par cela ? Avoir la liste des cadeaux que l'on souhaite offrir ?  
A ce moment là faire un présentation comme un panier de site de e commerce.

**Comment by patou** [comment]
Avoir sur une page la liste de tous les cadeaux que l'on compte offrir et à qui, et ainsi voir si on a bien tous les cadeaux pour tout le monde.
