### ISSUE TITLE
Pouvoir supprimer une envie

### ISSUE THREAD

**Issue by patou** [patou/liste-envies#8]

**Comment by manudss** [comment]
Cela implique, qui faut vérifier que personne ne l'ai pris. Que faire dans ce cas ? 
On peut aussi, indiquer, que ne le veux plus, ou qu'on nous l'a déjà offert.

**Comment by patou** [comment]
Heu, si on t'a donné le cadeau à Noël, après, tu supprime les cadeaux.
Pour moi, tu supprime même si quelqu'un a dit qu'il l'offre.

**Comment by patou** [comment]
Trois cas de Suppression : 

- Si c'est une envie et qui n'est pas prise => Suppression de la base de donnée
- Si l'envie est prise => Transformation en suggestion (les personnes qui ont offert, pourront la supprimer)
- Si c'est une suggestion => Seul la personne qui a créé la suggestion ou les personnes qui ont offert une envie qui a été supprimé, peuvent supprimer la suggestion.

Plus un bouton : Reçu :
- La personne peut cliquer sur un bouton reçu pour indiquer qu'il a bien reçu un cadeau, il est donc archivé.
- Pour les suggestion : La personnes qui ont offert ou participer au cadeau peuvent cliquer sur un bouton donner, pour archiver l'envie.
